using System;
using System.Collections.Generic;
using System.Globalization;
using Avalonia;
using Avalonia.Data.Converters;
using FluentIcons.Common;

namespace ClassScreenLock.Converters;

public class FontAwesomeToFluentIconConverter : IValueConverter
{
    public static readonly FontAwesomeToFluentIconConverter Instance = new();

    private static readonly Dictionary<string, Symbol> IconMapping = new(StringComparer.OrdinalIgnoreCase)
    {
        ["fas fa-chevron-left"] = Symbol.ChevronLeft,
        ["fas fa-chevron-right"] = Symbol.ChevronRight,
        ["fa-chevron-left"] = Symbol.ChevronLeft,
        ["fa-chevron-right"] = Symbol.ChevronRight,
        ["chevron-left"] = Symbol.ChevronLeft,
        ["chevron-right"] = Symbol.ChevronRight,
        ["fa-home"] = Symbol.Home,
        ["home"] = Symbol.Home,
        ["fa-calendar-days"] = Symbol.Calendar,
        ["calendar-days"] = Symbol.Calendar,
        ["fa-th-large"] = Symbol.Grid,
        ["th-large"] = Symbol.Grid,
        ["fa-network-wired"] = Symbol.Building,
        ["network-wired"] = Symbol.Building,
        ["fa-clipboard-list"] = Symbol.ClipboardText,
        ["clipboard-list"] = Symbol.ClipboardText,
        ["fas fa-user-shield"] = Symbol.ShieldPerson,
        ["fa-user-shield"] = Symbol.ShieldPerson,
        ["user-shield"] = Symbol.ShieldPerson,
        ["fas fa-camera"] = Symbol.Camera,
        ["fa-camera"] = Symbol.Camera,
        ["camera"] = Symbol.Camera,
        ["fas fa-video"] = Symbol.Video,
        ["fa-video"] = Symbol.Video,
        ["video"] = Symbol.Video,
        ["fas fa-robot"] = Symbol.Bot,
        ["fa-robot"] = Symbol.Bot,
        ["robot"] = Symbol.Bot,
        ["fa-sitemap"] = Symbol.Organization,
        ["sitemap"] = Symbol.Organization,
        ["fa-cog"] = Symbol.Settings,
        ["cog"] = Symbol.Settings,
        ["fa-info-circle"] = Symbol.Info,
        ["info-circle"] = Symbol.Info,
        ["fa-user"] = Symbol.Person,
        ["user"] = Symbol.Person,
        ["fa-user-circle"] = Symbol.PersonCircle,
        ["user-circle"] = Symbol.PersonCircle,
        ["fa-user-lock"] = Symbol.LockClosed,
        ["user-lock"] = Symbol.LockClosed,
        ["fa-user-slash"] = Symbol.PersonDelete,
        ["user-slash"] = Symbol.PersonDelete,
        ["fas fa-lock"] = Symbol.LockClosed,
        ["fa-lock"] = Symbol.LockClosed,
        ["lock"] = Symbol.LockClosed,
        ["fa-lock-open"] = Symbol.LockOpen,
        ["lock-open"] = Symbol.LockOpen,
        ["fas fa-unlock"] = Symbol.LockOpen,
        ["fa-unlock"] = Symbol.LockOpen,
        ["unlock"] = Symbol.LockOpen,
        ["fas fa-plus"] = Symbol.Add,
        ["fa-plus"] = Symbol.Add,
        ["plus"] = Symbol.Add,
        ["fas fa-bolt"] = Symbol.Flash,
        ["fa-bolt"] = Symbol.Flash,
        ["bolt"] = Symbol.Flash,
        ["fas fa-copy"] = Symbol.Copy,
        ["fa-copy"] = Symbol.Copy,
        ["copy"] = Symbol.Copy,
        ["fas fa-trash"] = Symbol.Delete,
        ["fa-trash"] = Symbol.Delete,
        ["trash"] = Symbol.Delete,
        ["fas fa-times"] = Symbol.Dismiss,
        ["fa-times"] = Symbol.Dismiss,
        ["times"] = Symbol.Dismiss,
        ["fas fa-check"] = Symbol.Checkmark,
        ["fa-check"] = Symbol.Checkmark,
        ["check"] = Symbol.Checkmark,
        ["fas fa-check-circle"] = Symbol.CheckmarkCircle,
        ["fa-check-circle"] = Symbol.CheckmarkCircle,
        ["check-circle"] = Symbol.CheckmarkCircle,
        ["fas fa-circle-xmark"] = Symbol.DismissCircle,
        ["fa-circle-xmark"] = Symbol.DismissCircle,
        ["circle-xmark"] = Symbol.DismissCircle,
        ["fas fa-triangle-exclamation"] = Symbol.Warning,
        ["fa-triangle-exclamation"] = Symbol.Warning,
        ["triangle-exclamation"] = Symbol.Warning,
        ["fas fa-bug"] = Symbol.Bug,
        ["fa-bug"] = Symbol.Bug,
        ["bug"] = Symbol.Bug,
        ["fas fa-shield"] = Symbol.Shield,
        ["fa-shield"] = Symbol.Shield,
        ["shield"] = Symbol.Shield,
        ["fas fa-shield-halved"] = Symbol.Shield,
        ["fa-shield-halved"] = Symbol.Shield,
        ["shield-halved"] = Symbol.Shield,
        ["fas fa-right-left"] = Symbol.ArrowSwap,
        ["fa-right-left"] = Symbol.ArrowSwap,
        ["right-left"] = Symbol.ArrowSwap,
        ["fas fa-desktop"] = Symbol.Desktop,
        ["fa-desktop"] = Symbol.Desktop,
        ["desktop"] = Symbol.Desktop,
        ["fas fa-chart-line"] = Symbol.Line,
        ["fa-chart-line"] = Symbol.Line,
        ["chart-line"] = Symbol.Line,
        ["fas fa-gears"] = Symbol.Settings,
        ["fa-gears"] = Symbol.Settings,
        ["gears"] = Symbol.Settings,
        ["fas fa-signs-post"] = Symbol.SignOut,
        ["fa-signs-post"] = Symbol.SignOut,
        ["signs-post"] = Symbol.SignOut,
        ["fas fa-database"] = Symbol.Database,
        ["fa-database"] = Symbol.Database,
        ["database"] = Symbol.Database,
        ["fas fa-undo"] = Symbol.ArrowUndo,
        ["fa-undo"] = Symbol.ArrowUndo,
        ["undo"] = Symbol.ArrowUndo,
        ["fas fa-redo"] = Symbol.ArrowRedo,
        ["fa-redo"] = Symbol.ArrowRedo,
        ["redo"] = Symbol.ArrowRedo,
        ["fas fa-file-lines"] = Symbol.Document,
        ["fa-file-lines"] = Symbol.Document,
        ["file-lines"] = Symbol.Document,
        ["fas fa-file"] = Symbol.Document,
        ["fa-file"] = Symbol.Document,
        ["file"] = Symbol.Document,
        ["fas fa-folder-open"] = Symbol.FolderOpen,
        ["fa-folder-open"] = Symbol.FolderOpen,
        ["folder-open"] = Symbol.FolderOpen,
        ["fas fa-eye"] = Symbol.Eye,
        ["fa-eye"] = Symbol.Eye,
        ["eye"] = Symbol.Eye,
        ["fas fa-eye-slash"] = Symbol.EyeOff,
        ["fa-eye-slash"] = Symbol.EyeOff,
        ["eye-slash"] = Symbol.EyeOff,
        ["fas fa-search-minus"] = Symbol.ZoomOut,
        ["fa-search-minus"] = Symbol.ZoomOut,
        ["search-minus"] = Symbol.ZoomOut,
        ["fas fa-search-plus"] = Symbol.ZoomIn,
        ["fa-search-plus"] = Symbol.ZoomIn,
        ["search-plus"] = Symbol.ZoomIn,
        ["fas fa-arrows-rotate"] = Symbol.ArrowSync,
        ["fa-arrows-rotate"] = Symbol.ArrowSync,
        ["arrows-rotate"] = Symbol.ArrowSync,
        ["fas fa-rotate"] = Symbol.ArrowSync,
        ["fa-rotate"] = Symbol.ArrowSync,
        ["rotate"] = Symbol.ArrowSync,
        ["fas fa-mouse-pointer"] = Symbol.Cursor,
        ["fa-mouse-pointer"] = Symbol.Cursor,
        ["mouse-pointer"] = Symbol.Cursor,
        ["fas fa-play"] = Symbol.Play,
        ["fa-play"] = Symbol.Play,
        ["play"] = Symbol.Play,
        ["fas fa-power-off"] = Symbol.Power,
        ["fa-power-off"] = Symbol.Power,
        ["power-off"] = Symbol.Power,
        ["fas fa-window-restore"] = Symbol.AppFolder,
        ["fa-window-restore"] = Symbol.AppFolder,
        ["window-restore"] = Symbol.AppFolder,
        ["fas fa-window-minimize"] = Symbol.AppFolder,
        ["fa-window-minimize"] = Symbol.AppFolder,
        ["window-minimize"] = Symbol.AppFolder,
        ["fas fa-window-maximize"] = Symbol.AppFolder,
        ["fa-window-maximize"] = Symbol.AppFolder,
        ["window-maximize"] = Symbol.AppFolder,
        ["fas fa-wifi"] = Symbol.Globe,
        ["fa-wifi"] = Symbol.Globe,
        ["wifi"] = Symbol.Globe,
        ["fas fa-ban"] = Symbol.Prohibited,
        ["fa-ban"] = Symbol.Prohibited,
        ["ban"] = Symbol.Prohibited,
        ["fas fa-link"] = Symbol.Link,
        ["fa-link"] = Symbol.Link,
        ["link"] = Symbol.Link,
        ["fas fa-image"] = Symbol.Image,
        ["fa-image"] = Symbol.Image,
        ["image"] = Symbol.Image,
        ["fas fa-volume-high"] = Symbol.Speaker2,
        ["fa-volume-high"] = Symbol.Speaker2,
        ["volume-high"] = Symbol.Speaker2,
        ["fas fa-chevron-up"] = Symbol.ChevronUp,
        ["fa-chevron-up"] = Symbol.ChevronUp,
        ["chevron-up"] = Symbol.ChevronUp,
        ["fas fa-chevron-down"] = Symbol.ChevronDown,
        ["fa-chevron-down"] = Symbol.ChevronDown,
        ["chevron-down"] = Symbol.ChevronDown,
        ["fas fa-arrow-left"] = Symbol.ArrowLeft,
        ["fa-arrow-left"] = Symbol.ArrowLeft,
        ["arrow-left"] = Symbol.ArrowLeft,
        ["fas fa-arrow-right"] = Symbol.ArrowRight,
        ["fa-arrow-right"] = Symbol.ArrowRight,
        ["arrow-right"] = Symbol.ArrowRight,
        ["fas fa-backspace"] = Symbol.Backspace,
        ["fa-backspace"] = Symbol.Backspace,
        ["backspace"] = Symbol.Backspace,
        ["fas fa-users"] = Symbol.People,
        ["fa-users"] = Symbol.People,
        ["users"] = Symbol.People,
        ["fas fa-user-plus"] = Symbol.PersonAdd,
        ["fa-user-plus"] = Symbol.PersonAdd,
        ["user-plus"] = Symbol.PersonAdd,
        ["fas fa-info-circle"] = Symbol.Info,
        ["info"] = Symbol.Info,
        ["fas fa-calendar-week"] = Symbol.CalendarWeekNumbers,
        ["fa-calendar-week"] = Symbol.CalendarWeekNumbers,
        ["calendar-week"] = Symbol.CalendarWeekNumbers,
    };

    public object? Convert(object? value, Type targetType, object? parameter, CultureInfo culture)
    {
        var icon = (value as string ?? string.Empty).Trim();
        
        if (IconMapping.TryGetValue(icon, out var symbol))
        {
            return symbol;
        }

        var normalizedIcon = icon.ToLowerInvariant()
            .Replace("fas ", "")
            .Replace("far ", "")
            .Replace("fab ", "")
            .Replace("fa-", "")
            .Trim();

        if (IconMapping.TryGetValue(normalizedIcon, out symbol))
        {
            return symbol;
        }

        return Symbol.QuestionCircle;
    }

    public object ConvertBack(object? value, Type targetType, object? parameter, CultureInfo culture)
    {
        return AvaloniaProperty.UnsetValue;
    }
}
