<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <Platform>x64</Platform>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
    <OutputPath>..\ClassScreenLock\bin\$(Configuration)\$(TargetFramework)\BreakButton\</OutputPath>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <Version>1.15.36.3545</Version>
    <AssemblyVersion>1.15.36.3545</AssemblyVersion>
    <FileVersion>1.15.36.3545</FileVersion>
    <InformationalVersion>1.15.36.3545</InformationalVersion>
    <Copyright>© 旧故里小牛（jiugulixiaoniu）</Copyright>
    <Authors>旧故里小牛（jiugulixiaoniu）</Authors>
    <Company>旧故里小牛（jiugulixiaoniu）</Company>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)' == 'Release'">
    <DebugType>none</DebugType>
    <DebugSymbols>false</DebugSymbols>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Avalonia" Version="11.3.10" />
    <PackageReference Include="Avalonia.Desktop" Version="11.3.10" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="11.3.10" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="11.3.10" />
  </ItemGroup>
</Project>
