<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Platform>x64</Platform>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    <OutputPath>..\ClassScreenLock\bin\$(Configuration)\$(TargetFramework)\Monitor\</OutputPath>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <Version>1.15.37.3639</Version>
    <AssemblyVersion>1.15.37.3639</AssemblyVersion>
    <FileVersion>1.15.37.3639</FileVersion>
    <InformationalVersion>1.15.37.3639</InformationalVersion>
    <Copyright>© 旧故里小牛（jiugulixiaoniu）</Copyright>
    <Authors>旧故里小牛（jiugulixiaoniu）</Authors>
    <Company>旧故里小牛（jiugulixiaoniu）</Company>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)' == 'Release'">
    <DebugType>none</DebugType>
    <DebugSymbols>false</DebugSymbols>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Diagnostics.PerformanceCounter" Version="9.0.0" />
  </ItemGroup>

</Project>
