<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net9.0-windows</TargetFramework>
        <Nullable>enable</Nullable>
        <Platform>x64</Platform>
        <ApplicationManifest>app.manifest</ApplicationManifest>
        <NuGetAudit>false</NuGetAudit>
        <DefineConstants Condition="'$(OS)' == 'Windows_NT'">$(DefineConstants);WINDOWS</DefineConstants>
        <Version>1.15.37.3639</Version>
        <AssemblyVersion>1.15.37.3639</AssemblyVersion>
        <FileVersion>1.15.37.3639</FileVersion>
        <InformationalVersion>1.15.37.3639</InformationalVersion>
        <Copyright>© 旧故里小牛（jiugulixiaoniu）</Copyright>
        <Authors>旧故里小牛（jiugulixiaoniu）</Authors>
        <Company>旧故里小牛（jiugulixiaoniu）</Company>
        <AssemblyName>CSL.Watchdog</AssemblyName>
        <ApplicationName>CSL.Watchdog</ApplicationName>
        <OutDir>..\ClassScreenLock\bin\$(Configuration)\$(TargetFramework)\</OutDir>
    </PropertyGroup>

    <PropertyGroup Condition="'$(Configuration)' == 'Release'">
        <DebugType>none</DebugType>
        <DebugSymbols>false</DebugSymbols>
        <PublishSingleFile>true</PublishSingleFile>
        <SelfContained>false</SelfContained>
        <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    </PropertyGroup>

    <PropertyGroup>
        <ApplicationManifest>app.manifest</ApplicationManifest>
        <ApplicationRequiresAdministrator>true</ApplicationRequiresAdministrator>
    </PropertyGroup>
</Project>
